AllCops:
  Exclude:
    - bin/**/*
    - spec/**/*
    - sermonaudio.gemspec

AccessorMethodName:
  Enabled: false

AmbiguousOperator:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Max: 80
